name: Append Link to PR to PR body
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  append-pr-link-to-pr-body:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const current = pr.body || "";
            const toAppend = `\n\nLink to PR: ${pr.html_url}`;
            const newBody = current + toAppend;
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              body: newBody
            });
