name: PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  validate-title:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: 'PR title must not start with a capital letter. Got: "${subject}"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

